### ISSUE TITLE
挂掉了 ！！！！

### ISSUE THREAD

**Issue by sevensevenmi** [isevenluo/github-hosts#4]
没记录了

**Comment by isevenluo** [comment]
家里网络有点访问，无法访问 https://www.ipaddress.com/
估计又是移动宽带的问题，之前也有过 github 不让访问，用电信的宽带就没有问题，你试下你的网络是否可以访问呢

**Comment by sevensevenmi** [comment]
这个 地址抽风了 无法访问 https://www.ipaddress.com/

**Comment by sevensevenmi** [comment]
> 家里网络有点访问，无法访问 https://www.ipaddress.com/ 估计又是移动宽带的问题，之前也有过 github 不让访问，用电信的宽带就没有问题，你试下你的网络是否可以访问呢

这个 地址抽风了 无法访问 https://www.ipaddress.com/

**Comment by sevensevenmi** [comment]
> 家里网络有点访问，无法访问 https://www.ipaddress.com/ 估计又是移动宽带的问题，之前也有过 github 不让访问，用电信的宽带就没有问题，你试下你的网络是否可以访问呢

已经活了

**Comment by mingjiezhou** [comment]
连续三天没更新了？我的 vscode 插件 Live Host 依赖你这个接口 大佬

**Comment by isevenluo** [comment]
> 连续三天没更新了？我的 vscode 插件 Live Host 依赖你这个接口 大佬
抱歉，前两天太忙没有处理，现在已经恢复了
