### ISSUE TITLE
gitee的怎么搞 被加权限了

### ISSUE THREAD

**Issue by sevensevenmi** [isevenluo/github-hosts#5]
为了营造绿色健康的开源社区，推动中国开源生态建设，当前仓库仅限成员访问。
你可以联系仓库管理员提交公开仓库访问的申请。
如果你是仓库持有者，请检查你是否处于登陆状态。

**Comment by sevensevenmi** [comment]
公开仓库要求审核后才允许公开。
您是管理员的话
您可以申请一下
审核通过就可以了

**Comment by isevenluo** [comment]
@sevensevenmi 已经提交申请了。你知道这个被收权限的原因？我明明是开源库怎么突然不让访问了

**Comment by isevenluo** [comment]
> 公开仓库要求审核后才允许公开。 您是管理员的话 您可以申请一下 审核通过就可以了

你直接用github上的内容吧，gitee项目显示涉及代理被强制不可访问了，国内这个原因你懂的
