### ISSUE TITLE
https://cdn.jsdelivr.net/gh/coderluojust/github-hosts/hosts 下载下来内容是空的怎么回事

### ISSUE THREAD

**Issue by xtdyzw2018** [isevenluo/github-hosts#9]
你好，使用switchhosts后，本机hosts内容如下：
# GitHub Host Start

# Please Star: https://github.com/isevenluo/github-hosts
# Please Star: https://gitee.com/isevenluo/github-hosts
# Update at: 2022年12月7日 下午3:56:20

# GitHub Host End

**Comment by isevenluo** [comment]
已经修复，你再试下，如果有问题请随时反馈。源码也开源了，代码逻辑也比较简单，下次可以尝试下修复，提pr过来哦

**Comment by happyTonakai** [comment]
Empty again

**Comment by isevenluo** [comment]
> Empty again
addressed. Thank you for your feedback, I forgot to update the jar package for the local service
